In [2]:
import numpy as np
from tqdm import tqdm

Ponemos los datos de los premios basados en los que hubo el 13 de septiembre de 2023

In [3]:
elegido = np.array([6,23,17,7,32,14])
premios = [0,0,0,0,1935.96,465168.75,125000000]
precio = 100

In [4]:
def sortearQuini6():
    """
    Sortea 6 números para un juego de Quini6.
    
    Genera un array de 6 números enteros aleatorios sin reemplazo, 
    cada uno de los cuales se encuentra en el rango de 0 a 45 (inclusive).
    
    Returns
    -------
    np.ndarray
        Un array de NumPy que contiene 6 números enteros aleatorios.
        
    Examples
    --------
    >>> sortearQuini6()
    array([12, 35, 8, 22, 14, 40])
    
    >>> sortearQuini6()
    array([ 2, 31, 27,  9, 22,  7])
    
    Notes
    -----
    La función utiliza la biblioteca NumPy para generar números aleatorios.
    """
    return np.random.choice(range(46), size = 6,replace = False)

In [10]:
ganador = sortearQuini6()

In [11]:
ganador

array([14,  5, 19, 10, 15, 39])

In [12]:
def simularQuini6(elegido, n):
    """
    Simula un número determinado de sorteos de Quini6 y cuenta los aciertos.
    
    Realiza `n` simulaciones de sorteos de Quini6 y compara cada resultado
    con un conjunto de números `elegido`. Almacena el número de aciertos
    en un contador.
    
    Parameters
    ----------
    elegido : list of int
        Los números elegidos para comparar con los números sorteados.
        
    n : int
        Número de simulaciones a realizar.
        
    Returns
    -------
    list of int
        Una lista de 7 elementos, donde el elemento en el índice `i` 
        representa el número de sorteos en los que se acertaron exactamente 
        `i` números.
        
    Examples
    --------
    >>> simularQuini6([1, 2, 3, 4, 5, 6], 10000)
    [9520, 420, 50, 8, 1, 0, 1]
    
    Notes
    -----
    Esta función utiliza la biblioteca tqdm para mostrar una barra de progreso,
    así como NumPy para la generación de números aleatorios.
    
    """
    contador = [0,0,0,0,0,0,0]
    for aux in tqdm(range(n)):
        ganador = sortearQuini6()
        contador[sum([True for x in elegido if x in ganador])] += 1
    return contador

In [13]:
contador = simularQuini6(elegido, 100)

contador

100%|███████████████████████████████████████| 100/100 [00:00<00:00, 6953.42it/s]


[41, 45, 14, 0, 0, 0, 0]

In [14]:
def calcularGanancias(contador, premios, precio):
    """
    Calcula las ganancias totales a partir de un contador de aciertos, una lista de premios y el precio por juego.
    
    Multiplica cada elemento del contador por su premio correspondiente, suma estos productos
    y resta el costo total de las jugadas para obtener las ganancias netas.
    
    Parameters
    ----------
    contador : list of int
        Una lista de 7 elementos, donde el elemento en el índice `i`
        representa el número de sorteos en los que se acertaron exactamente `i` números.
        
    premios : list of float
        Una lista de 7 elementos, donde el elemento en el índice `i`
        representa el premio en dinero por acertar exactamente `i` números.
        
    precio : float
        El costo en dinero de una sola jugada de Quini6.
        
    Returns
    -------
    float
        Las ganancias netas calculadas a partir del contador de aciertos, los premios y el precio por jugada.
        
    Examples
    --------
    >>> calcularGanancias([9520, 420, 50, 8, 1, 0, 1], [0, 10, 100, 1000, 10000, 100000, 1000000], 2)
    94920.0
    
    Notes
    -----
    La función utiliza la biblioteca NumPy para operaciones vectorizadas.
    """
    
    return sum(contador * np.array(premios)) - sum(contador) * precio 

In [22]:
contador = simularQuini6(elegido, 1000000)

contador

100%|██████████████████████████████| 1000000/1000000 [01:13<00:00, 13680.79it/s]


[409133, 421798, 146618, 21149, 1266, 36, 0]

In [23]:
calcularGanancias(contador, premios, precio)

-80802999.64